name: flutter_onjung
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_analytics: ^11.4.1
  flutter_riverpod: ^2.3.4
  fluttertoast: ^8.2.2
  image_picker: ^0.8.7+3
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.8
  uuid: ^3.0.6
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/welcome_image.png

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700

  uses-material-design: true
